// Generated by CoffeeScript 1.6.3
var app, express, http, middleware, path, routes, _i, _len, _ref;

require('./data/db').connect();

express = require('express');

routes = require('./routes');

http = require('http');

path = require('path');

app = express();

app.set('port', process.env.PORT || 5000);

app.set('views', __dirname + '/views');

app.set('view engine', 'jade');

_ref = [express.favicon(), express.logger('dev'), express.bodyParser(), express.methodOverride(), express.cookieParser('TOP$ECRET'), express.session(), app.router, express["static"](path.join(__dirname, 'public'))];
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  middleware = _ref[_i];
  app.use(middleware);
}

if (app.get('env') === 'development') {
  app.use(express.errorHandler());
}

routes.create(app);

http.createServer(app).listen(app.get('port'), function() {
  return console.log('Express server listening on port ' + app.get('port'));
});
