// Generated by CoffeeScript 1.6.3
var home, user;

user = require('./user');

home = function(req, res) {
  return res.render('index', {
    title: 'What Matters Most'
  });
};

exports.create = function(app) {
  app.get('/', home);
  return user.create(app);
};
