// Generated by CoffeeScript 1.6.3
var home, tweet, tweetStory, user, webcam, youtubeStory;

var user = require('./user')
  , tweetStory = require('./tweetStory')
  , youtubeStory = require('./youtubeStory');

function home(req, res) {
    return res.render('index', {
        title: 'What Matters Most'
    });
};

function tweet(req, res) {
    return res.render('tweet');
}

function webcam(req, res) {
    return res.render('webcam');
}

exports.create = function(app) {
    app.get('/', home);
    app.get('/tweet', tweet);
    app.get('/webcam', webcam);
    user.create(app);
    tweetStory.create(app);
    youtubeStory.create(app);
};
