// Generated by CoffeeScript 1.6.3
var User;

User = require('../data/user').User;

exports.list = function(req, res) {
  return res.send("respond with a resource");
};

exports.test = function(req, res) {
  var testing;
  testing = new User({
    name: "Some Guy",
    email: "some.guy@gmail.com",
    joinDate: Date.now(),
    age: 22,
    category: "Student",
    location: "Needham, MA"
  });
  testing.save(function(err) {
    if (err) {
      return console.log(err);
    }
  });
  return res.send("Hey there");
};
