// Generated by CoffeeScript 1.6.3
exports.fail = function(res, error) {
  return res.json({
    success: false,
    error: error
  });
};

exports.succeed = function(res, resultObj) {
  if (resultObj == null) {
    resultObj = {};
  }
  resultObj.success = true;
  return res.json(resultObj);
};

exports.optional = function(defaultValue, fun) {
  return function(req, res) {
    var e;
    try {
      return fun(req, res);
    } catch (_error) {
      e = _error;
      return defaultValue;
    }
  };
};

exports.doCheck = function(req, res, fun) {
  var e;
  try {
    return [false, fun(req, res)];
  } catch (_error) {
    e = _error;
    exports.fail(res, e.message);
    return [true, null];
  }
};

exports.checkAll = function(req, res, fields) {
  var checker, err, name, result, value, _ref;
  result = {};
  for (name in fields) {
    checker = fields[name];
    _ref = exports.doCheck(req, res, checker), err = _ref[0], value = _ref[1];
    if (err) {
      return [true, result];
    }
    result[name] = value;
  }
  return [false, result];
};
